on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Dump event_path
      run: |
        cat ${{ github.event_path }}
